#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/axentra/axentra /usr/bin/axentra

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/axentra.service ]; then
			rm /etc/systemd/system/axentra.service /usr/lib/systemd/system/axentra.service /usr/lib/systemd/user/axentra.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/axentra/files/systemd/axentra.service /usr/lib/systemd/system/axentra.service
		# try fix error in Ubuntu 18.04
		# Failed to reload axentra.service: Unit axentra.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/axentra.service:10: Executable path is not absolute: pkill -f "axentra --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/axentra.service
		fi
		systemctl daemon-reload
		systemctl enable axentra
		systemctl start axentra
	fi
fi

